spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""

  jpa:
    database: H2
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 0

application:
  topic:
    product-created-event-topic: "product-created-events-topic"